// Generated by scripts/build-themes.mjs. Do not edit.

export interface ThemeSwatch {
	bg: string;
	fg: string;
	primary: string;
	accent: string;
	muted: string;
}

export const THEMES: { id: string; label: string; light: ThemeSwatch; dark: ThemeSwatch }[] = [
	{
		id: 'caffeine',
		label: 'Caffeine',
		light: {
			bg: 'oklch(0.9821 0 0)',
			fg: 'oklch(0.2435 0 0)',
			primary: 'oklch(0.4341 0.0392 41.9938)',
			accent: 'oklch(0.9310 0 0)',
			muted: 'oklch(0.9521 0 0)'
		},
		dark: {
			bg: 'oklch(0.1776 0 0)',
			fg: 'oklch(0.9491 0 0)',
			primary: 'oklch(0.9247 0.0524 66.1732)',
			accent: 'oklch(0.2850 0 0)',
			muted: 'oklch(0.2520 0 0)'
		}
	},
	{
		id: 'catppuccin',
		label: 'Catppuccin',
		light: {
			bg: 'oklch(0.9578 0.0058 264.5321)',
			fg: 'oklch(0.4355 0.0430 279.3250)',
			primary: 'oklch(0.5547 0.2503 297.0156)',
			accent: 'oklch(0.6820 0.1448 235.3822)',
			muted: 'oklch(0.9060 0.0117 264.5071)'
		},
		dark: {
			bg: 'oklch(0.2155 0.0254 284.0647)',
			fg: 'oklch(0.8787 0.0426 272.2767)',
			primary: 'oklch(0.7871 0.1187 304.7693)',
			accent: 'oklch(0.8467 0.0833 210.2545)',
			muted: 'oklch(0.2973 0.0294 276.2144)'
		}
	},
	{
		id: 'claude',
		label: 'Claude',
		light: {
			bg: 'oklch(0.9818 0.0054 95.0986)',
			fg: 'oklch(0.3438 0.0269 95.7226)',
			primary: 'oklch(0.6171 0.1375 39.0427)',
			accent: 'oklch(0.9245 0.0138 92.9892)',
			muted: 'oklch(0.9341 0.0153 90.2390)'
		},
		dark: {
			bg: 'oklch(0.2679 0.0036 106.6427)',
			fg: 'oklch(0.8074 0.0142 93.0137)',
			primary: 'oklch(0.6724 0.1308 38.7559)',
			accent: 'oklch(0.2130 0.0078 95.4245)',
			muted: 'oklch(0.2213 0.0038 106.7070)'
		}
	},
	{
		id: 'cosmic-night',
		label: 'Cosmic Night',
		light: {
			bg: 'oklch(0.9730 0.0133 286.1503)',
			fg: 'oklch(0.3015 0.0572 282.4176)',
			primary: 'oklch(0.5417 0.1790 288.0332)',
			accent: 'oklch(0.9221 0.0373 262.1410)',
			muted: 'oklch(0.9580 0.0133 286.1454)'
		},
		dark: {
			bg: 'oklch(0.1743 0.0227 283.7998)',
			fg: 'oklch(0.9185 0.0257 285.8834)',
			primary: 'oklch(0.7162 0.1597 290.3962)',
			accent: 'oklch(0.3354 0.0828 280.9705)',
			muted: 'oklch(0.2710 0.0621 281.4377)'
		}
	},
	{
		id: 'graphite',
		label: 'Graphite',
		light: {
			bg: 'oklch(0.9551 0 0)',
			fg: 'oklch(0.3211 0 0)',
			primary: 'oklch(0.4891 0 0)',
			accent: 'oklch(0.8078 0 0)',
			muted: 'oklch(0.8853 0 0)'
		},
		dark: {
			bg: 'oklch(0.2178 0 0)',
			fg: 'oklch(0.8853 0 0)',
			primary: 'oklch(0.7058 0 0)',
			accent: 'oklch(0.3715 0 0)',
			muted: 'oklch(0.2850 0 0)'
		}
	},
	{
		id: 'gruvbox',
		label: 'Gruvbox',
		light: {
			bg: '#fbf1c7',
			fg: '#3c3836',
			primary: '#b57614',
			accent: '#d5c4a1',
			muted: '#ebdbb2'
		},
		dark: {
			bg: '#282828',
			fg: '#ebdbb2',
			primary: '#fabd2f',
			accent: '#504945',
			muted: '#3c3836'
		}
	},
	{
		id: 'kodama-grove',
		label: 'Kodama Grove',
		light: {
			bg: 'oklch(0.8798 0.0534 91.7893)',
			fg: 'oklch(0.4265 0.0310 59.2153)',
			primary: 'oklch(0.6657 0.1050 118.9078)',
			accent: 'oklch(0.8361 0.0713 90.3269)',
			muted: 'oklch(0.8532 0.0631 91.1493)'
		},
		dark: {
			bg: 'oklch(0.3303 0.0214 88.0737)',
			fg: 'oklch(0.9217 0.0235 82.1191)',
			primary: 'oklch(0.6762 0.0567 132.4479)',
			accent: 'oklch(0.6540 0.0723 90.7629)',
			muted: 'oklch(0.3892 0.0197 82.7084)'
		}
	},
	{
		id: 'mono',
		label: 'Mono',
		light: {
			bg: 'oklch(1.0000 0 0)',
			fg: 'oklch(0.1448 0 0)',
			primary: 'oklch(0.5555 0 0)',
			accent: 'oklch(0.9702 0 0)',
			muted: 'oklch(0.9702 0 0)'
		},
		dark: {
			bg: 'oklch(0.1448 0 0)',
			fg: 'oklch(0.9851 0 0)',
			primary: 'oklch(0.5555 0 0)',
			accent: 'oklch(0.3715 0 0)',
			muted: 'oklch(0.2686 0 0)'
		}
	},
	{
		id: 'ocean-breeze',
		label: 'Ocean Breeze',
		light: {
			bg: 'oklch(0.9751 0.0127 244.2507)',
			fg: 'oklch(0.3729 0.0306 259.7328)',
			primary: 'oklch(0.7227 0.1920 149.5793)',
			accent: 'oklch(0.9505 0.0507 163.0508)',
			muted: 'oklch(0.9670 0.0029 264.5419)'
		},
		dark: {
			bg: 'oklch(0.2077 0.0398 265.7549)',
			fg: 'oklch(0.8717 0.0093 258.3382)',
			primary: 'oklch(0.7729 0.1535 163.2231)',
			accent: 'oklch(0.3729 0.0306 259.7328)',
			muted: 'oklch(0.2463 0.0275 259.9628)'
		}
	},
	{
		id: 'solar-dusk',
		label: 'Solar Dusk',
		light: {
			bg: 'oklch(0.9885 0.0057 84.5659)',
			fg: 'oklch(0.3660 0.0251 49.6085)',
			primary: 'oklch(0.5553 0.1455 48.9975)',
			accent: 'oklch(0.9000 0.0500 74.9889)',
			muted: 'oklch(0.9363 0.0218 83.2637)'
		},
		dark: {
			bg: 'oklch(0.2161 0.0061 56.0434)',
			fg: 'oklch(0.9699 0.0013 106.4238)',
			primary: 'oklch(0.7049 0.1867 47.6044)',
			accent: 'oklch(0.3598 0.0497 229.3202)',
			muted: 'oklch(0.2330 0.0073 67.4563)'
		}
	},
	{
		id: 'supabase',
		label: 'Supabase',
		light: {
			bg: 'oklch(0.9911 0 0)',
			fg: 'oklch(0.2046 0 0)',
			primary: 'oklch(0.8348 0.1302 160.9080)',
			accent: 'oklch(0.9461 0 0)',
			muted: 'oklch(0.9461 0 0)'
		},
		dark: {
			bg: 'oklch(0.1822 0 0)',
			fg: 'oklch(0.9288 0.0126 255.5078)',
			primary: 'oklch(0.4365 0.1044 156.7556)',
			accent: 'oklch(0.3132 0 0)',
			muted: 'oklch(0.2393 0 0)'
		}
	},
	{
		id: 't3-chat',
		label: 'T3 Chat',
		light: {
			bg: 'oklch(0.9754 0.0084 325.6414)',
			fg: 'oklch(0.3257 0.1161 325.0372)',
			primary: 'oklch(0.5316 0.1409 355.1999)',
			accent: 'oklch(0.8696 0.0675 334.8991)',
			muted: 'oklch(0.9395 0.0260 331.5454)'
		},
		dark: {
			bg: 'oklch(0.2409 0.0201 307.5346)',
			fg: 'oklch(0.8398 0.0387 309.5391)',
			primary: 'oklch(0.4607 0.1853 4.0994)',
			accent: 'oklch(0.3649 0.0508 308.4911)',
			muted: 'oklch(0.2634 0.0219 309.4748)'
		}
	},
	{
		id: 'twitter',
		label: 'Twitter',
		light: {
			bg: 'oklch(1.0000 0 0)',
			fg: 'oklch(0.1884 0.0128 248.5103)',
			primary: 'oklch(0.6723 0.1606 244.9955)',
			accent: 'oklch(0.9392 0.0166 250.8453)',
			muted: 'oklch(0.9222 0.0013 286.3737)'
		},
		dark: {
			bg: 'oklch(0 0 0)',
			fg: 'oklch(0.9328 0.0025 228.7857)',
			primary: 'oklch(0.6692 0.1607 245.0110)',
			accent: 'oklch(0.1928 0.0331 242.5459)',
			muted: 'oklch(0.2090 0 0)'
		}
	},
	{
		id: 'vercel',
		label: 'Vercel',
		light: {
			bg: 'oklch(0.9900 0 0)',
			fg: 'oklch(0 0 0)',
			primary: 'oklch(0 0 0)',
			accent: 'oklch(0.9400 0 0)',
			muted: 'oklch(0.9700 0 0)'
		},
		dark: {
			bg: 'oklch(0 0 0)',
			fg: 'oklch(1 0 0)',
			primary: 'oklch(1 0 0)',
			accent: 'oklch(0.3200 0 0)',
			muted: 'oklch(0.2300 0 0)'
		}
	},
	{
		id: 'vintage-paper',
		label: 'Vintage Paper',
		light: {
			bg: 'oklch(0.9582 0.0152 90.2357)',
			fg: 'oklch(0.3760 0.0225 64.3434)',
			primary: 'oklch(0.6180 0.0778 65.5444)',
			accent: 'oklch(0.8348 0.0426 88.8064)',
			muted: 'oklch(0.9239 0.0190 83.0636)'
		},
		dark: {
			bg: 'oklch(0.2747 0.0139 57.6523)',
			fg: 'oklch(0.9239 0.0190 83.0636)',
			primary: 'oklch(0.7264 0.0581 66.6967)',
			accent: 'oklch(0.4186 0.0281 56.3404)',
			muted: 'oklch(0.2939 0.0125 62.1298)'
		}
	}
];
