export interface MarkIconOption {
	id: string;
	keywords: string;
}

export const LUCIDE_ICONS: MarkIconOption[] = [
	{ id: 'bug', keywords: 'bug defect error' },
	{ id: 'sparkles', keywords: 'feature new magic' },
	{ id: 'flame', keywords: 'fire hot incident urgent' },
	{ id: 'shield', keywords: 'security protect' },
	{ id: 'shield-alert', keywords: 'security vulnerability' },
	{ id: 'rocket', keywords: 'launch release ship' },
	{ id: 'wrench', keywords: 'fix tool maintenance' },
	{ id: 'hammer', keywords: 'build tool' },
	{ id: 'package', keywords: 'dependency package npm' },
	{ id: 'book-open', keywords: 'docs documentation read' },
	{ id: 'file-text', keywords: 'docs file text' },
	{ id: 'palette', keywords: 'design color' },
	{ id: 'paintbrush', keywords: 'design style' },
	{ id: 'test-tube', keywords: 'test experiment' },
	{ id: 'flask-conical', keywords: 'experiment lab' },
	{ id: 'gauge', keywords: 'performance speed' },
	{ id: 'zap', keywords: 'fast quick lightning' },
	{ id: 'database', keywords: 'data database sql' },
	{ id: 'server', keywords: 'backend server infra' },
	{ id: 'cloud', keywords: 'cloud infra' },
	{ id: 'lock', keywords: 'security private' },
	{ id: 'key', keywords: 'auth key secret' },
	{ id: 'globe', keywords: 'web website world' },
	{ id: 'smartphone', keywords: 'mobile phone app' },
	{ id: 'monitor', keywords: 'desktop screen frontend' },
	{ id: 'code', keywords: 'code programming' },
	{ id: 'terminal', keywords: 'cli terminal shell' },
	{ id: 'git-branch', keywords: 'branch git' },
	{ id: 'git-merge', keywords: 'merge git' },
	{ id: 'git-pull-request', keywords: 'pull request pr' },
	{ id: 'layers', keywords: 'stack layers' },
	{ id: 'puzzle', keywords: 'plugin integration' },
	{ id: 'lightbulb', keywords: 'idea' },
	{ id: 'star', keywords: 'favorite important' },
	{ id: 'heart', keywords: 'love like' },
	{ id: 'flag', keywords: 'flag milestone' },
	{ id: 'bookmark', keywords: 'save bookmark' },
	{ id: 'tag', keywords: 'tag label' },
	{ id: 'folder', keywords: 'folder project' },
	{ id: 'inbox', keywords: 'inbox triage' },
	{ id: 'bell', keywords: 'notification alert' },
	{ id: 'megaphone', keywords: 'announcement marketing' },
	{ id: 'message-square', keywords: 'comment chat discussion' },
	{ id: 'users', keywords: 'team people' },
	{ id: 'user', keywords: 'person' },
	{ id: 'bot', keywords: 'bot automation ai' },
	{ id: 'calendar', keywords: 'date schedule' },
	{ id: 'clock', keywords: 'time' },
	{ id: 'timer', keywords: 'timer deadline' },
	{ id: 'hourglass', keywords: 'waiting' },
	{ id: 'target', keywords: 'goal target' },
	{ id: 'trophy', keywords: 'win award' },
	{ id: 'chart-line', keywords: 'analytics metrics chart' },
	{ id: 'chart-bar', keywords: 'analytics chart stats' },
	{ id: 'trending-up', keywords: 'growth' },
	{ id: 'dollar-sign', keywords: 'money billing revenue' },
	{ id: 'credit-card', keywords: 'payments billing' },
	{ id: 'shopping-cart', keywords: 'ecommerce shop' },
	{ id: 'truck', keywords: 'delivery shipping' },
	{ id: 'map-pin', keywords: 'location' },
	{ id: 'compass', keywords: 'explore navigation' },
	{ id: 'anchor', keywords: 'anchor' },
	{ id: 'leaf', keywords: 'green nature' },
	{ id: 'sprout', keywords: 'new growth' },
	{ id: 'tree-pine', keywords: 'tree nature' },
	{ id: 'sun', keywords: 'day light' },
	{ id: 'moon', keywords: 'night dark' },
	{ id: 'snowflake', keywords: 'freeze cold' },
	{ id: 'umbrella', keywords: 'cover insurance' },
	{ id: 'coffee', keywords: 'break chore' },
	{ id: 'pizza', keywords: 'food' },
	{ id: 'gift', keywords: 'gift reward' },
	{ id: 'music', keywords: 'music audio' },
	{ id: 'camera', keywords: 'photo camera' },
	{ id: 'image', keywords: 'image picture' },
	{ id: 'video', keywords: 'video' },
	{ id: 'mic', keywords: 'audio voice' },
	{ id: 'headphones', keywords: 'support audio' },
	{ id: 'gamepad-2', keywords: 'game' },
	{ id: 'graduation-cap', keywords: 'learn education' },
	{ id: 'briefcase', keywords: 'work business' },
	{ id: 'building', keywords: 'company office' },
	{ id: 'house', keywords: 'home' },
	{ id: 'scale', keywords: 'legal balance' },
	{ id: 'gavel', keywords: 'legal law' },
	{ id: 'stethoscope', keywords: 'health' },
	{ id: 'pill', keywords: 'health medicine' },
	{ id: 'activity', keywords: 'activity monitoring' },
	{ id: 'triangle-alert', keywords: 'warning alert' },
	{ id: 'circle-alert', keywords: 'alert warning' },
	{ id: 'octagon-alert', keywords: 'stop danger' },
	{ id: 'ban', keywords: 'blocked stop' },
	{ id: 'circle-check', keywords: 'done check' },
	{ id: 'eye', keywords: 'watch review' },
	{ id: 'search', keywords: 'search find' },
	{ id: 'funnel', keywords: 'filter' },
	{ id: 'settings', keywords: 'settings config' },
	{ id: 'sliders-horizontal', keywords: 'settings tune' },
	{ id: 'recycle', keywords: 'refactor reuse' },
	{ id: 'archive', keywords: 'archive old' },
	{ id: 'box', keywords: 'box' },
	{ id: 'boxes', keywords: 'packages' },
	{ id: 'cpu', keywords: 'cpu hardware' },
	{ id: 'hard-drive', keywords: 'storage disk' },
	{ id: 'wifi', keywords: 'network' },
	{ id: 'link', keywords: 'link url' },
	{ id: 'paperclip', keywords: 'attachment' },
	{ id: 'pen-tool', keywords: 'design vector' },
	{ id: 'pencil', keywords: 'edit write' },
	{ id: 'scissors', keywords: 'cut' },
	{ id: 'ruler', keywords: 'measure' },
	{ id: 'brush', keywords: 'clean style' },
	{ id: 'feather', keywords: 'light writing' },
	{ id: 'languages', keywords: 'i18n translation' },
	{ id: 'accessibility', keywords: 'a11y accessibility' },
	{ id: 'dog', keywords: 'dog pet' },
	{ id: 'cat', keywords: 'cat pet' },
	{ id: 'fish', keywords: 'fish' },
	{ id: 'bird', keywords: 'bird' },
	{ id: 'shapes', keywords: 'category shapes' },
	{ id: 'construction', keywords: 'wip construction' },
	{ id: 'traffic-cone', keywords: 'wip caution' },
	{ id: 'siren', keywords: 'incident emergency' },
	{ id: 'skull', keywords: 'danger dead' },
	{ id: 'ghost', keywords: 'ghost stale' },
	{ id: 'crown', keywords: 'vip owner' },
	{ id: 'gem', keywords: 'gem quality' }
];

export const EMOJI: MarkIconOption[] = [
	{ id: '🐛', keywords: 'bug' },
	{ id: '✨', keywords: 'sparkles feature new' },
	{ id: '🔥', keywords: 'fire hot incident' },
	{ id: '🚨', keywords: 'siren alert incident' },
	{ id: '🚀', keywords: 'rocket launch release' },
	{ id: '🔧', keywords: 'wrench fix' },
	{ id: '🛠️', keywords: 'tools maintenance' },
	{ id: '📦', keywords: 'package dependency' },
	{ id: '📚', keywords: 'books docs' },
	{ id: '📝', keywords: 'memo notes docs' },
	{ id: '🎨', keywords: 'art design' },
	{ id: '🧪', keywords: 'test' },
	{ id: '⚡', keywords: 'zap fast' },
	{ id: '🗄️', keywords: 'database cabinet' },
	{ id: '☁️', keywords: 'cloud' },
	{ id: '🔒', keywords: 'lock security' },
	{ id: '🔑', keywords: 'key auth' },
	{ id: '🌐', keywords: 'globe web' },
	{ id: '📱', keywords: 'phone mobile' },
	{ id: '💻', keywords: 'laptop code' },
	{ id: '🖥️', keywords: 'desktop' },
	{ id: '⌨️', keywords: 'keyboard' },
	{ id: '🧩', keywords: 'puzzle plugin' },
	{ id: '💡', keywords: 'idea' },
	{ id: '⭐', keywords: 'star' },
	{ id: '❤️', keywords: 'heart' },
	{ id: '🚩', keywords: 'flag' },
	{ id: '🏷️', keywords: 'label tag' },
	{ id: '📁', keywords: 'folder' },
	{ id: '📥', keywords: 'inbox' },
	{ id: '🔔', keywords: 'bell' },
	{ id: '📣', keywords: 'megaphone announce' },
	{ id: '💬', keywords: 'speech comment' },
	{ id: '👥', keywords: 'people team' },
	{ id: '🤖', keywords: 'robot bot' },
	{ id: '📅', keywords: 'calendar' },
	{ id: '⏰', keywords: 'alarm clock' },
	{ id: '⏳', keywords: 'hourglass waiting' },
	{ id: '🎯', keywords: 'target goal' },
	{ id: '🏆', keywords: 'trophy' },
	{ id: '📈', keywords: 'chart up growth' },
	{ id: '📊', keywords: 'bar chart analytics' },
	{ id: '💰', keywords: 'money' },
	{ id: '💳', keywords: 'card payments' },
	{ id: '🛒', keywords: 'cart shop' },
	{ id: '🚚', keywords: 'truck delivery' },
	{ id: '📍', keywords: 'pin location' },
	{ id: '🧭', keywords: 'compass' },
	{ id: '🌱', keywords: 'seedling new' },
	{ id: '🌲', keywords: 'tree' },
	{ id: '☀️', keywords: 'sun' },
	{ id: '🌙', keywords: 'moon' },
	{ id: '❄️', keywords: 'snow freeze' },
	{ id: '☕', keywords: 'coffee' },
	{ id: '🍕', keywords: 'pizza' },
	{ id: '🎁', keywords: 'gift' },
	{ id: '🎵', keywords: 'music' },
	{ id: '📷', keywords: 'camera' },
	{ id: '🎬', keywords: 'video film' },
	{ id: '🎙️', keywords: 'mic' },
	{ id: '🎧', keywords: 'headphones support' },
	{ id: '🎮', keywords: 'game' },
	{ id: '🎓', keywords: 'graduation learn' },
	{ id: '💼', keywords: 'briefcase work' },
	{ id: '🏢', keywords: 'office building' },
	{ id: '🏠', keywords: 'house home' },
	{ id: '⚖️', keywords: 'scale legal' },
	{ id: '🩺', keywords: 'health' },
	{ id: '💊', keywords: 'pill' },
	{ id: '⚠️', keywords: 'warning' },
	{ id: '❗', keywords: 'exclamation important' },
	{ id: '❓', keywords: 'question' },
	{ id: '⛔', keywords: 'no entry blocked' },
	{ id: '🚫', keywords: 'prohibited blocked' },
	{ id: '✅', keywords: 'check done' },
	{ id: '👀', keywords: 'eyes review watch' },
	{ id: '🔍', keywords: 'search' },
	{ id: '⚙️', keywords: 'gear settings' },
	{ id: '♻️', keywords: 'recycle refactor' },
	{ id: '🗃️', keywords: 'archive' },
	{ id: '🧹', keywords: 'broom cleanup chore' },
	{ id: '🧱', keywords: 'brick infra' },
	{ id: '🔗', keywords: 'link' },
	{ id: '📎', keywords: 'paperclip' },
	{ id: '✏️', keywords: 'pencil edit' },
	{ id: '✂️', keywords: 'scissors' },
	{ id: '📏', keywords: 'ruler' },
	{ id: '🖌️', keywords: 'brush' },
	{ id: '🌍', keywords: 'earth world i18n' },
	{ id: '♿', keywords: 'accessibility' },
	{ id: '🐶', keywords: 'dog' },
	{ id: '🐱', keywords: 'cat' },
	{ id: '🐟', keywords: 'fish' },
	{ id: '🐦', keywords: 'bird' },
	{ id: '🦔', keywords: 'hedgehog posthog' },
	{ id: '🚧', keywords: 'construction wip' },
	{ id: '💀', keywords: 'skull' },
	{ id: '👻', keywords: 'ghost' },
	{ id: '👑', keywords: 'crown' },
	{ id: '💎', keywords: 'gem' },
	{ id: '🔴', keywords: 'red circle' },
	{ id: '🟠', keywords: 'orange circle' },
	{ id: '🟡', keywords: 'yellow circle' },
	{ id: '🟢', keywords: 'green circle' },
	{ id: '🔵', keywords: 'blue circle' },
	{ id: '🟣', keywords: 'purple circle' },
	{ id: '⚫', keywords: 'black circle' },
	{ id: '⚪', keywords: 'white circle' },
	{ id: '👍', keywords: 'thumbs up' },
	{ id: '👎', keywords: 'thumbs down' },
	{ id: '🙏', keywords: 'thanks please' },
	{ id: '🎉', keywords: 'party celebrate' },
	{ id: '😴', keywords: 'sleep later' },
	{ id: '🤔', keywords: 'thinking question' },
	{ id: '😬', keywords: 'grimace risky' },
	{ id: '🧠', keywords: 'brain ai' },
	{ id: '🛡️', keywords: 'shield security' },
	{ id: '🧯', keywords: 'fire extinguisher' },
	{ id: '🪲', keywords: 'beetle bug' },
	{ id: '📌', keywords: 'pushpin' },
	{ id: '🗓️', keywords: 'calendar plan' },
	{ id: '📤', keywords: 'outbox' },
	{ id: '📨', keywords: 'incoming envelope' },
	{ id: '🧾', keywords: 'receipt billing' },
	{ id: '🏗️', keywords: 'building construction' },
	{ id: '🧰', keywords: 'toolbox' },
	{ id: '🔬', keywords: 'microscope research' },
	{ id: '📡', keywords: 'antenna' },
	{ id: '🔋', keywords: 'battery' },
	{ id: '🔌', keywords: 'plug integration' }
];

export const LUCIDE_PREFIX = 'lucide:';
const MAX_EMOJI_CHARS = 16;
const EMOJI_PATTERN = /^\p{Extended_Pictographic}/u;

export type MarkIcon = { kind: 'lucide'; id: string } | { kind: 'emoji'; text: string };

export function parseMarkIcon(icon: string | undefined): MarkIcon | null {
	if (!icon) return null;
	if (icon.startsWith(LUCIDE_PREFIX)) {
		const id = icon.slice(LUCIDE_PREFIX.length);
		return LUCIDE_ICONS.some((i) => i.id === id) ? { kind: 'lucide', id } : null;
	}
	return icon.length <= MAX_EMOJI_CHARS && EMOJI_PATTERN.test(icon)
		? { kind: 'emoji', text: icon }
		: null;
}

export function searchIcons(options: MarkIconOption[], query: string): MarkIconOption[] {
	const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
	if (!words.length) return options;
	return options.filter((o) => {
		const text = `${o.id} ${o.keywords}`.toLowerCase();
		return words.every((w) => text.includes(w));
	});
}
