// Download shadcn themes from the tweakcn registry and write them as CSS the app ships.
// Run again to update: `node scripts/build-themes.mjs`. The app never fetches themes at run time.
import { writeFileSync } from 'node:fs';

const THEMES = [
	['claude', 'Claude'],
	['vercel', 'Vercel'],
	['supabase', 'Supabase'],
	['catppuccin', 'Catppuccin'],
	['graphite', 'Graphite'],
	['mono', 'Mono'],
	['caffeine', 'Caffeine'],
	['ocean-breeze', 'Ocean Breeze'],
	['kodama-grove', 'Kodama Grove'],
	['solar-dusk', 'Solar Dusk'],
	['cosmic-night', 'Cosmic Night'],
	['vintage-paper', 'Vintage Paper'],
	['t3-chat', 'T3 Chat'],
	['twitter', 'Twitter']
];

// Themes that tweakcn does not have, written here from their official palettes. Same keys as
// tweakcn's cssVars. `signal-*` also colors Hush's own states (review, CI failure, merge…).
const LOCAL = {
	// https://github.com/morhetz/gruvbox (light: the "light" palette; dark: the "dark" palette).
	gruvbox: {
		label: 'Gruvbox',
		radius: '0.375rem',
		light: {
			background: '#fbf1c7',
			foreground: '#3c3836',
			card: '#f9f5d7',
			'card-foreground': '#3c3836',
			popover: '#f9f5d7',
			'popover-foreground': '#3c3836',
			primary: '#b57614',
			'primary-foreground': '#fbf1c7',
			secondary: '#ebdbb2',
			'secondary-foreground': '#3c3836',
			muted: '#ebdbb2',
			'muted-foreground': '#7c6f64',
			accent: '#d5c4a1',
			'accent-foreground': '#3c3836',
			destructive: '#9d0006',
			'destructive-foreground': '#fbf1c7',
			border: '#d5c4a1',
			input: '#bdae93',
			ring: '#b57614',
			'chart-1': '#af3a03',
			'chart-2': '#79740e',
			'chart-3': '#076678',
			'chart-4': '#8f3f71',
			'chart-5': '#427b58',
			sidebar: '#f2e5bc',
			'sidebar-foreground': '#3c3836',
			'sidebar-primary': '#b57614',
			'sidebar-primary-foreground': '#fbf1c7',
			'sidebar-accent': '#ebdbb2',
			'sidebar-accent-foreground': '#3c3836',
			'sidebar-border': '#d5c4a1',
			'sidebar-ring': '#b57614',
			'signal-review': '#076678',
			'signal-fail': '#9d0006',
			'signal-merge': '#79740e',
			'signal-reply': '#8f3f71',
			'signal-warn': '#b57614'
		},
		dark: {
			background: '#282828',
			foreground: '#ebdbb2',
			card: '#32302f',
			'card-foreground': '#ebdbb2',
			popover: '#32302f',
			'popover-foreground': '#ebdbb2',
			primary: '#fabd2f',
			'primary-foreground': '#282828',
			secondary: '#3c3836',
			'secondary-foreground': '#ebdbb2',
			muted: '#3c3836',
			'muted-foreground': '#a89984',
			accent: '#504945',
			'accent-foreground': '#ebdbb2',
			destructive: '#fb4934',
			'destructive-foreground': '#282828',
			border: '#504945',
			input: '#665c54',
			ring: '#fabd2f',
			'chart-1': '#fe8019',
			'chart-2': '#b8bb26',
			'chart-3': '#83a598',
			'chart-4': '#d3869b',
			'chart-5': '#8ec07c',
			sidebar: '#1d2021',
			'sidebar-foreground': '#ebdbb2',
			'sidebar-primary': '#fabd2f',
			'sidebar-primary-foreground': '#282828',
			'sidebar-accent': '#3c3836',
			'sidebar-accent-foreground': '#ebdbb2',
			'sidebar-border': '#3c3836',
			'sidebar-ring': '#fabd2f',
			'signal-review': '#83a598',
			'signal-fail': '#fb4934',
			'signal-merge': '#b8bb26',
			'signal-reply': '#d3869b',
			'signal-warn': '#fabd2f'
		}
	}
};

// Only colors and the corner radius: fonts would need downloads, and shadows and spacing would
// change the layout.
const skip = (k) => /^(font-|shadow|tracking|spacing|letter-spacing)/.test(k);

const sources = [
	...THEMES.map(([name, label]) => ({ name, label })),
	...Object.entries(LOCAL).map(([name, t]) => ({ name, label: t.label, local: t }))
].sort((a, b) => a.label.localeCompare(b.label));

const blocks = [];
const list = [];
for (const { name, label, local } of sources) {
	let cssVars;
	if (local) cssVars = { theme: { radius: local.radius }, light: local.light, dark: local.dark };
	else {
		const res = await fetch(`https://tweakcn.com/r/themes/${name}.json`);
		if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
		({ cssVars } = await res.json());
	}
	const radius = cssVars.theme?.radius ?? cssVars.light?.radius;
	const vars = (o) =>
		Object.entries(o)
			.filter(([k]) => !skip(k) && k !== 'radius')
			.map(([k, v]) => `\t--${k}: ${v};`)
			.join('\n');
	blocks.push(
		`html[data-theme='${name}'] {\n${vars(cssVars.light)}${radius ? `\n\t--radius: ${radius};` : ''}\n}\nhtml.dark[data-theme='${name}'] {\n${vars(cssVars.dark)}\n}`
	);
	const sw = (o) => ({
		bg: o.background,
		fg: o.foreground,
		primary: o.primary,
		accent: o.accent,
		muted: o.muted
	});
	list.push({ id: name, label, light: sw(cssVars.light), dark: sw(cssVars.dark) });
}

writeFileSync(
	'src/lib/themes/themes.css',
	`/* Generated by scripts/build-themes.mjs from https://tweakcn.com (shadcn themes) and the palettes\n   in that script. Do not edit. */\n\n${blocks.join('\n\n')}\n`
);
writeFileSync(
	'src/lib/themes/list.ts',
	`// Generated by scripts/build-themes.mjs. Do not edit.\n\nexport interface ThemeSwatch {\n\tbg: string;\n\tfg: string;\n\tprimary: string;\n\taccent: string;\n\tmuted: string;\n}\n\nexport const THEMES: { id: string; label: string; light: ThemeSwatch; dark: ThemeSwatch }[] = ${JSON.stringify(list, null, '\t')};\n`
);
console.log(`Wrote ${list.length} themes.`);
